---
- hosts: 172.31.35.35
  become: yes
  tasks:
  - name: install git
    apt:
      name: git

  - name: install tree
    apt:
      namee: tree
    ignore_errors: yes
  
  - name: install wget
    apt:
      name: wget
